<?php

namespace WeatherBundle\Repository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCitiesByName($name)
    {
        $queryBuilder = $this->createQueryBuilder('c');
        $queryBuilder->select('c')
            ->where("c.name LIKE :name")
            ->setParameter(":name", $name);



        return $queryBuilder->getQuery()->getResult();

    }
}
