<?php

namespace WeatherBundle\Repository;

/**
 * DataSourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataSourceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBetweenLatLng()
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT ds FROM dataSource as ds ORDER BY ds.name ASC")
            ->getResult();
    }
}
