<?php

namespace WeatherBundle\Repository;

/**
 * DataSourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataSourceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBetweenLatLng()
    {
        return $ds = $this->getEntityManager()
                    ->createQueryBuilder('ds')
            ->select()
            ->where('ds.id < 2');

            //->getResult();

        //echo dump($ds->getResult());
        //exit;
    }
}
